services:
  server:
    build: ./server
    container_name: Container_server
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      SECRET_KEY: "9813kbk31023khvviuytyuwqkiwvj9mnb757uytr34nm123o"
      REFRESH_SECRET_KEY: "y87238giehgaiuwgd82o123455gskiassmnxzxclaoihdsobk"
      NODE_ENV: "development"
      PORT: 3001
      MIDTRANS_SERVER_KEY: SB-Mid-server-zw-LJ6-UHTMlabcfbM06qqvz
      MIDTRANS_SANDBOX_URL: "https://app.sandbox.midtrans.com/snap/v1/transactions"
      MIDTRANS_PRODUCTION_URL: ''
      DB_DIALECT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_NAME: "amra_db"
      DB_USER: "amra_user"
      DB_PASS: "amra_password"
    depends_on:
      - mysql
    networks:
      - app-network

  client:
    # build: ./client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: Container_client
    ports:
      - "5173:5173"  # port Vue dev server default
    environment:
      - VITE_APP_API_BASE_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: amra_db
      MYSQL_USER: amra_user
      MYSQL_PASSWORD: amra_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_config/my.cnf:/etc/mysql/my.cnf  # Mount file my.cnf ke dalam container
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
