'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Pakets', [
      { 
        division_id: 1, 
        jenis_kegiatan: 'umrah',
        kode: 'OJP137',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Keren',
        name: 'Umrah Keren',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-08-30', 
        return_date: '2025-09-12',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-08-30 05:02:00',
        arrival_time: '2025-09-12 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
      { 
        division_id: 1, 
        jenis_kegiatan: 'umrah',
        kode: 'AABBCC',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Maret-Bareng-Ustad',
        name: 'Umrah Maret Bareng Ustad',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-07-10', 
        return_date: '2025-08-12',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-05-17 05:02:00',
        arrival_time: '2025-05-18 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
      { 
        division_id: 2, 
        jenis_kegiatan: 'umrah',
        kode: 'FFGGHH',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Ramadhan',
        name: 'Umrah Ramadhan Sebulan Penuh',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-10-10', 
        return_date: '2025-10-30',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-05-17 05:02:00',
        arrival_time: '2025-05-18 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
      { 
        division_id: 1, 
        jenis_kegiatan: 'umrah',
        kode: 'GGRREE',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Bulan-Pertama-Tahun-2025',
        name: 'Umrah Bulan Pertama Tahun 2025',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-12-10', 
        return_date: '2025-12-30',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-05-17 05:02:00',
        arrival_time: '2025-05-18 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
      { 
        division_id: 1, 
        jenis_kegiatan: 'umrah',
        kode: 'GGRREE',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Bulan-Desember',
        name: 'Umrah Bulan Desember',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-08-10', 
        return_date: '2025-09-12',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-05-17 05:02:00',
        arrival_time: '2025-05-18 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
      { 
        division_id: 2, 
        jenis_kegiatan: 'umrah',
        kode: 'GGRREE',
        photo: '/uploads/daftar_paket/1746170299194.jpg',
        slug: 'Umrah-Bulan-Januari-2026',
        name: 'Umrah Bulan Januari 2026',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 
        departure_date: '2025-08-10', 
        return_date: '2025-10-12',
        departure_from: 2,
        duration_trip: 7,
        mahram_fee: 300000,
        quota_jamaah: 40,
        city_visited: '[{"id":"2"},{"id":"4"},{"id":"6"},{"id":"1"},{"id":"5"},{"id":"3"}]',
        airlines: '[{"id":"2"},{"id":"1"}]',
        hotel: '[{"id":"4"},{"id":"1"},{"id":"2"},{"id":"3"}]',
        facilities: '[{"id":"5"},{"id":"2"},{"id":"1"},{"id":"3"},{"id":"4"}]',
        show_homepage: 'tampilkan',
        airport_departure: 1,
        airport_destination: 4,
        departure_time: '2025-05-17 05:02:00',
        arrival_time: '2025-05-18 05:02:00',
        tutup_paket: 'buka',
        provider_visa_id: 1,
        asuransi_id: 1, 
        no_polis: 123456,
        tgl_input_polis: '2025-05-17', 
        tgl_awal_polis: '2025-05-01',
        tgl_akhir_polis: '2025-06-07',
        createdAt: new Date(), 
        updatedAt: new Date() 
      },
    ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Pakets', null, {});
  }
};